In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import requests

In [9]:
root_dir=os.getcwd()+'/'

# Data Download

In [10]:
# download me data
url = 'https://biendata.com/competition/meteorology/bj/2018-02-01-0/2018-05-31-23/2k0d1d8'
respones= requests.get(url)
with open (root_dir+"bj_me_180331-180531.csv",'w') as f:
    f.write(respones.text)

In [11]:
# download aq data
url = 'https://biendata.com/competition/airquality/bj/2018-03-31-0/2018-05-31-23/2k0d1d8'
respones= requests.get(url)
with open (root_dir+"bj_aq_180331-180531.csv",'w') as f:
    f.write(respones.text)

# Data Concat

## Air Quality Concat

In [34]:
# load data
df0_aq_p1=pd.read_csv(root_dir+'beijing_201802_201803_aq.csv')
df0_aq_p2=pd.read_csv(root_dir+'bj_aq_180331-180531.csv')

# change colname
colname4p2=list(str('i'))
colname4p2.extend(list(df0_aq_p1.columns))
df0_aq_p2.columns=colname4p2

In [36]:
# data show
# df0_aq_p1
df0_aq_p2

,i,stationId,utc_time,PM2.5,PM10,NO2,CO,O3,SO2
0,2941450,dongsi_aq,2018-03-31 07:00:00,105.0,172.0,53.0,0.8,127.0,14.0
1,2941451,tiantan_aq,2018-03-31 07:00:00,95.0,123.0,54.0,0.9,121.0,15.0
2,2941452,guanyuan_aq,2018-03-31 07:00:00,95.0,139.0,66.0,0.8,123.0,13.0
3,2941453,wanshouxigong_aq,2018-03-31 07:00:00,99.0,172.0,58.0,1.0,119.0,14.0
4,2941454,aotizhongxin_aq,2018-03-31 07:00:00,117.0,166.0,67.0,0.8,111.0,14.0
5,2941455,nongzhanguan_aq,2018-03-31 07:00:00,100.0,150.0,62.0,0.8,127.0,15.0
6,2941456,wanliu_aq,2018-03-31 07:00:00,95.0,139.0,82.0,1.0,104.0,13.0
7,2941457,beibuxinqu_aq,2018-03-31 07:00:00,104.0,236.0,75.0,0.9,98.0,9.0
8,2941458,zhiwuyuan_aq,2018-03-31 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN
9,2941459,fengtaihuayuan_aq,2018-03-31 07:00:00,111.0,162.0,65.0,0.9,119.0,13.0
10,2941460,yungang_aq,2018-03-31 07:00:00,106.0,171.0,68.0,0.9,117.0,13.0
11,2941461,gucheng_aq,2018-03-31 07:00:00,133.0,193.0,79.0,0.9,110.0,10.0
12,2941462,fangshan_aq,2018-03-31 07:00:00,102.0,188.0,66.0,0.7,131.0,13.0
13,2941463,daxing_aq,2018-03-31 07:00:00,92.0,156.0,43.0,0.8,139.0,14.0
14,2941464,yizhuang_aq,2018-03-31 07:00:00,90.0,148.0,42.0,0.9,153.0,18.0
15,2941465,tongzhou_aq,2018-03-31 07:00:00,105.0,146.0,38.0,0.7,138.0,16.0
16,2941466,shunyi_aq,2018-03-31 07:00:00,104.0,143.0,52.0,1.0,142.0,16.0
17,2941467,pingchang_aq,2018-03-31 07:00:00,85.0,133.0,52.0,0.9,117.0,12.0
18,2941468,mentougou_aq,2018-03-31 07:00:00,96.0,169.0,75.0,0.8,120.0,11.0
19,2941469,pinggu_aq,2018-03-31 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN
20,2941470,huairou_aq,2018-03-31 07:00:00,86.0,125.0,52.0,0.8,124.0,12.0
21,2941471,miyun_aq,2018-03-31 07:00:00,80.0,125.0,37.0,0.7,159.0,10.0
22,2941472,yanqin_aq,2018-03-31 07:00:00,54.0,259.0,15.0,0.4,121.0,5.0
23,2941473,dingling_aq,2018-03-31 07:00:00,82.0,142.0,45.0,0.9,130.0,10.0
24,2941474,badaling_aq,2018-03-31 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN
25,2941475,miyunshuiku_aq,2018-03-31 07:00:00,92.0,133.0,27.0,0.7,169.0,9.0
26,2941476,donggaocun_aq,2018-03-31 07:00:00,136.0,150.0,49.0,1.5,143.0,33.0
27,2941477,yongledian_aq,2018-03-31 07:00:00,106.0,172.0,52.0,1.2,170.0,16.0
28,2941478,yufa_aq,2018-03-31 07:00:00,121.0,183.0,53.0,0.8,141.0,17.0
29,2941479,liulihe_aq,2018-03-31 07:00:00,105.0,163.0,45.0,0.8,137.0,6.0
...,...,...,...,...,...,...,...,...,...
48550,3021262,nongzhanguan_aq,2018-05-31 23:00:00,37.0,89.0,122.0,0.7,7.0,3.0
48551,3021263,wanliu_aq,2018-05-31 23:00:00,29.0,116.0,111.0,0.7,13.0,2.0
48552,3021264,beibuxinqu_aq,2018-05-31 23:00:00,23.0,61.0,69.0,0.6,29.0,2.0
48553,3021265,zhiwuyuan_aq,2018-05-31 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN
48554,3021266,fengtaihuayuan_aq,2018-05-31 23:00:00,38.0,110.0,69.0,0.7,32.0,3.0
48555,3021267,yungang_aq,2018-05-31 23:00:00,18.0,46.0,24.0,0.4,107.0,2.0
48556,3021268,gucheng_aq,2018-05-31 23:00:00,38.0,60.0,82.0,0.6,64.0,2.0
48557,3021269,fangshan_aq,2018-05-31 23:00:00,25.0,103.0,78.0,0.5,75.0,4.0
48558,3021270,daxing_aq,2018-05-31 23:00:00,52.0,251.0,117.0,0.7,2.0,5.0
48559,3021271,yizhuang_aq,2018-05-31 23:00:00,46.0,171.0,127.0,1.0,8.0,10.0
48560,3021272,tongzhou_aq,2018-05-31 23:00:00,22.0,124.0,86.0,0.6,27.0,4.0
48561,3021273,shunyi_aq,2018-05-31 23:00:00,26.0,58.0,44.0,0.5,80.0,2.0
48562,3021274,pingchang_aq,2018-05-31 23:00:00,20.0,62.0,74.0,0.4,58.0,2.0
48563,3021275,mentougou_aq,2018-05-31 23:00:00,18.0,53.0,23.0,0.4,133.0,2.0
48564,3021276,pinggu_aq,2018-05-31 23:00:00,24.0,49.0,36.0,0.5,105.0,2.0
48565,3021277,huairou_aq,2018-05-31 23:00:00,21.0,57.0,25.0,0.5,97.0,2.0
48566,3021278,miyun_aq,2018-05-31 23:00:00,26.0,54.0,46.0,0.4,86.0,2.0
48567,3021279,yanqin_aq,2018-05-31 23:00:00,28.0,78.0,69.0,0.4,45.0,3.0
48568,3021280,dingling_aq,2018-05-31 23:00:00,13.0,46.0,14.0,0.3,108.0,2.0
48569,3021281,badaling_aq,2018-05-31 23:00:00,23.0,81.0,101.0,0.4,47.0,3.0
48570,3021282,miyunshuiku_aq,2018-05-31 23:00:00,21.0,45.0,20.0,0.4,107.0,3.0
48571,3021283,donggaocun_aq,2018-05-31 23:00:00,30.0,121.0,14.0,0.3,83.0,6.0
48572,3021284,yongledian_aq,2018-05-31 23:00:00,41.0,98.0,72.0,1.1,4.0,4.0
48573,3021285,yufa_aq,2018-05-31 23:00:00,71.0,148.0,55.0,0.6,26.0,12.0
48574,3021286,liulihe_aq,2018-05-31 23:00:00,43.0,170.0,42.0,0.5,46.0,2.0
48575,3021287,qianmen_aq,2018-05-31 23:00:00,44.0,83.0,112.0,0.7,27.0,5.0
48576,3021288,yongdingmennei_aq,2018-05-31 23:00:00,47.0,140.0,143.0,0.9,2.0,10.0
48577,3021289,xizhimenbei_aq,2018-05-31 23:00:00,39.0,90.0,127.0,0.7,18.0,4.0
48578,3021290,nansanhuan_aq,2018-05-31 23:00:00,56.0,157.0,138.0,0.9,6.0,7.0
48579,3021291,dongsihuan_aq,2018-05-31 23:00:00,58.0,145.0,140.0,0.8,3.0,9.0

In [46]:
def uniq_aver(df_aq):
    # unique 
    time_aq,ind_aq=np.unique(df_aq['utc_time'],return_inverse=True)
    # average over all stations
    pollution=np.zeros(len(time_aq))
    for i in range(len(time_aq)):
        pollution[i]=np.nanmean(df_aq[ind_aq==i]['PM2.5'])
    # create new df
    df1_aq=pd.DataFrame({
        'utc_time':time_aq,
        'PM2.5':pollution
    })
    return df1_aq

In [47]:
# unify the dataframe
df1_aq_p1=uniq_aver(df0_aq_p1)
df1_aq_p2=uniq_aver(df0_aq_p2)

In [50]:
# show 
#df1_aq_p1
df1_aq_p2.iloc[9:,:]

           PM2.5             utc_time
9     149.515152  2018-03-31 17:00:00
10    145.727273  2018-03-31 18:00:00
11    141.757576  2018-03-31 19:00:00
12    139.151515  2018-03-31 20:00:00
13    139.818182  2018-03-31 21:00:00
14    152.303030  2018-03-31 22:00:00
15    163.151515  2018-03-31 23:00:00
16    220.303030  2018-04-01 02:00:00
17    234.882353  2018-04-01 03:00:00
18    239.529412  2018-04-01 04:00:00
19    243.500000  2018-04-01 05:00:00
20    237.941176  2018-04-01 06:00:00
21    178.764706  2018-04-01 08:00:00
22    148.852941  2018-04-01 09:00:00
23    129.176471  2018-04-01 10:00:00
24    131.333333  2018-04-01 11:00:00
25    154.941176  2018-04-01 12:00:00
26    173.029412  2018-04-01 13:00:00
27    180.235294  2018-04-01 15:00:00
28    174.205882  2018-04-01 17:00:00
29    176.235294  2018-04-01 18:00:00
30    187.617647  2018-04-01 19:00:00
31    205.794118  2018-04-01 20:00:00
32    220.588235  2018-04-01 21:00:00
33    227.647059  2018-04-01 22:00:00
34    229.676471  2018-04-01 23:00:00
35    256.588235  2018-04-02 01:00:00
36    271.088235  2018-04-02 02:00:00
37    280.500000  2018-04-02 03:00:00
38    279.090909  2018-04-02 04:00:00
...          ...                  ...
1358   28.848485  2018-05-30 18:00:00
1359   31.147059  2018-05-30 19:00:00
1360   32.470588  2018-05-30 20:00:00
1361   37.823529  2018-05-30 21:00:00
1362   41.088235  2018-05-30 22:00:00
1363   44.441176  2018-05-30 23:00:00
1364   47.294118  2018-05-31 00:00:00
1365   45.852941  2018-05-31 01:00:00
1366   39.205882  2018-05-31 02:00:00
1367   37.781250  2018-05-31 03:00:00
1368   33.090909  2018-05-31 04:00:00
1369   27.937500  2018-05-31 05:00:00
1370   22.000000  2018-05-31 06:00:00
1371   19.878788  2018-05-31 07:00:00
1372   20.666667  2018-05-31 08:00:00
1373   21.235294  2018-05-31 09:00:00
1374   19.352941  2018-05-31 10:00:00
1375   21.882353  2018-05-31 11:00:00
1376   23.558824  2018-05-31 12:00:00
1377   25.125000  2018-05-31 13:00:00
1378   30.029412  2018-05-31 14:00:00
1379   30.294118  2018-05-31 15:00:00
1380   27.882353  2018-05-31 16:00:00
1381   29.470588  2018-05-31 17:00:00
1382   29.176471  2018-05-31 18:00:00
1383   30.882353  2018-05-31 19:00:00
1384   32.000000  2018-05-31 20:00:00
1385   32.264706  2018-05-31 21:00:00
1386   33.058824  2018-05-31 22:00:00
1387   33.676471  2018-05-31 23:00:00

[1379 rows x 2 columns]

In [52]:
df1_aq=df1_aq_p1.append(df1_aq_p2.iloc[9:,:], ignore_index=True)
df1_aq

          PM2.5             utc_time
0     50.840000  2018-01-31 16:00:00
1     47.823529  2018-01-31 17:00:00
2     47.235294  2018-01-31 18:00:00
3     46.411765  2018-01-31 19:00:00
4     44.764706  2018-01-31 20:00:00
5     42.160000  2018-01-31 21:00:00
6     39.240000  2018-01-31 22:00:00
7     40.970588  2018-01-31 23:00:00
8     40.600000  2018-02-01 00:00:00
9     46.117647  2018-02-01 01:00:00
10    48.727273  2018-02-01 02:00:00
11    48.264706  2018-02-01 03:00:00
12    45.029412  2018-02-01 04:00:00
13    40.781250  2018-02-01 05:00:00
14    37.272727  2018-02-01 06:00:00
15    36.941176  2018-02-01 07:00:00
16    33.529412  2018-02-01 08:00:00
17    30.823529  2018-02-01 09:00:00
18    29.090909  2018-02-01 10:00:00
19    23.240000  2018-02-01 11:00:00
20    15.558824  2018-02-01 12:00:00
21     9.484848  2018-02-01 13:00:00
22     7.000000  2018-02-01 14:00:00
23     6.200000  2018-02-01 15:00:00
24     5.960000  2018-02-01 16:00:00
25     6.794118  2018-02-01 17:00:00
26     6.200000  2018-02-01 18:00:00
27     6.480000  2018-02-01 19:00:00
28     6.840000  2018-02-01 20:00:00
29     6.818182  2018-02-01 21:00:00
...         ...                  ...
2761  28.848485  2018-05-30 18:00:00
2762  31.147059  2018-05-30 19:00:00
2763  32.470588  2018-05-30 20:00:00
2764  37.823529  2018-05-30 21:00:00
2765  41.088235  2018-05-30 22:00:00
2766  44.441176  2018-05-30 23:00:00
2767  47.294118  2018-05-31 00:00:00
2768  45.852941  2018-05-31 01:00:00
2769  39.205882  2018-05-31 02:00:00
2770  37.781250  2018-05-31 03:00:00
2771  33.090909  2018-05-31 04:00:00
2772  27.937500  2018-05-31 05:00:00
2773  22.000000  2018-05-31 06:00:00
2774  19.878788  2018-05-31 07:00:00
2775  20.666667  2018-05-31 08:00:00
2776  21.235294  2018-05-31 09:00:00
2777  19.352941  2018-05-31 10:00:00
2778  21.882353  2018-05-31 11:00:00
2779  23.558824  2018-05-31 12:00:00
2780  25.125000  2018-05-31 13:00:00
2781  30.029412  2018-05-31 14:00:00
2782  30.294118  2018-05-31 15:00:00
2783  27.882353  2018-05-31 16:00:00
2784  29.470588  2018-05-31 17:00:00
2785  29.176471  2018-05-31 18:00:00
2786  30.882353  2018-05-31 19:00:00
2787  32.000000  2018-05-31 20:00:00
2788  32.264706  2018-05-31 21:00:00
2789  33.058824  2018-05-31 22:00:00
2790  33.676471  2018-05-31 23:00:00

[2791 rows x 2 columns]

In [67]:
df1_aq.describe()

             PM2.5
count  2791.000000
mean     67.243122
std      56.416858
min       4.941176
25%      25.894545
50%      49.529412
75%      93.500000
max     330.588235

## Meteological Data Concat

In [59]:
# load data
df0_me_p1=pd.read_csv(root_dir+'beijing_201802_201803_me.csv')
df0_me_p2=pd.read_csv(root_dir+'bj_me_180331-180531.csv')

# change colname
colname4p2=list(str('i'))
colname4p2.extend(list(df0_me_p1.columns))
df0_me_p2.columns=colname4p2

In [60]:
# show 
# df0_me_p1
df0_me_p2

,i,station_id,utc_time,weather,temperature,pressure,humidity,wind_speed,wind_direction
0,2001610,shunyi_meo,2018-03-31 07:00:00,Sunny/clear,23.4,1006.9,19.0,3.3,212.0
1,2001611,hadian_meo,2018-03-31 07:00:00,Sunny/clear,23.7,1004.8,19.0,1.6,191.0
2,2001612,yanqing_meo,2018-03-31 07:00:00,Sunny/clear,25.8,952.5,14.0,5.4,247.0
3,2001613,miyun_meo,2018-03-31 07:00:00,Hail,23.9,1001.4,19.0,3.9,232.0
4,2001614,huairou_meo,2018-03-31 07:00:00,Sunny/clear,22.6,1001.3,19.0,3.2,243.0
5,2001615,shangdianzi_meo,2018-03-31 07:00:00,Sunny/clear,22.7,975.1,19.0,7.1,239.0
6,2001616,pinggu_meo,2018-03-31 07:00:00,Sunny/clear,23.2,1006.4,20.0,2.9,231.0
7,2001617,tongzhou_meo,2018-03-31 07:00:00,Hail,23.4,1008.0,19.0,1.2,205.0
8,2001618,chaoyang_meo,2018-03-31 07:00:00,Sunny/clear,23.2,1006.4,20.0,2.9,207.0
9,2001619,pingchang_meo,2018-03-31 07:00:00,Sunny/clear,23.5,1001.3,16.0,3.1,172.0
10,2001620,zhaitang_meo,2018-03-31 07:00:00,Sunny/clear,25.6,957.8,14.0,5.3,45.0
11,2001621,mentougou_meo,2018-03-31 07:00:00,Sunny/clear,23.3,1000.6,18.0,3.1,76.0
12,2001622,beijing_meo,2018-03-31 07:00:00,Hail,23.7,1006.6,20.0,1.7,162.0
13,2001623,shijingshan_meo,2018-03-31 07:00:00,Sunny/clear,23.5,1002.9,17.0,2.6,198.0
14,2001624,fengtai,2018-03-31 07:00:00,Sunny/clear,23.9,1004.0,18.0,2.6,219.0
15,2001625,daxing,2018-03-31 07:00:00,Sunny/clear,23.3,1005.9,19.0,2.5,167.0
16,2001626,fangshan,2018-03-31 07:00:00,Sunny/clear,23.8,1004.8,12.0,1.6,243.0
17,2001627,xiayunling_meo,2018-03-31 07:00:00,Sunny/clear,23.0,962.9,21.0,5.1,187.0
18,2002491,shunyi_meo,2018-03-31 08:00:00,Sunny/clear,23.4,1006.2,20.0,3.9,210.0
19,2002492,hadian_meo,2018-03-31 08:00:00,Sunny/clear,23.8,1004.0,20.0,1.7,194.0
20,2002493,yanqing_meo,2018-03-31 08:00:00,Sunny/clear,25.2,951.8,14.0,3.3,206.0
21,2002494,miyun_meo,2018-03-31 08:00:00,Hail,23.4,1001.0,20.0,3.8,223.0
22,2002495,huairou_meo,2018-03-31 08:00:00,Sunny/clear,23.0,1000.6,20.0,2.9,206.0
23,2002496,shangdianzi_meo,2018-03-31 08:00:00,Sunny/clear,21.6,974.7,21.0,8.4,246.0
24,2002497,pinggu_meo,2018-03-31 08:00:00,Sunny/clear,23.3,1005.9,22.0,3.6,225.0
25,2002498,tongzhou_meo,2018-03-31 08:00:00,Hail,23.7,1007.3,20.0,2.9,187.0
26,2002499,chaoyang_meo,2018-03-31 08:00:00,Sunny/clear,23.2,1005.6,21.0,2.3,180.0
27,2002500,pingchang_meo,2018-03-31 08:00:00,Sunny/clear,23.6,1000.6,17.0,1.8,171.0
28,2002501,zhaitang_meo,2018-03-31 08:00:00,Sunny/clear,23.8,957.7,16.0,4.1,39.0
29,2002502,mentougou_meo,2018-03-31 08:00:00,Sunny/clear,23.3,999.8,19.0,2.9,284.0
...,...,...,...,...,...,...,...,...,...
25828,4219871,pinggu_meo,2018-05-31 22:00:00,Sunny/clear,17.5,1010.4,66.0,0.8,43.0
25829,4219872,tongzhou_meo,2018-05-31 22:00:00,Sunny/clear,16.9,1011.7,91.0,0.9,324.0
25830,4219873,chaoyang_meo,2018-05-31 22:00:00,Sunny/clear,21.1,1010.2,52.0,1.0,82.0
25831,4219874,pingchang_meo,2018-05-31 22:00:00,Sunny/clear,19.5,1005.5,50.0,1.3,333.0
25832,4219875,zhaitang_meo,2018-05-31 22:00:00,Sunny/clear,14.0,965.4,69.0,0.8,50.0
25833,4219876,mentougou_meo,2018-05-31 22:00:00,Sunny/clear,21.0,1004.4,43.0,2.5,323.0
25834,4219877,beijing_meo,2018-05-31 22:00:00,Sunny/clear,21.3,1010.3,52.0,1.1,58.0
25835,4219878,shijingshan_meo,2018-05-31 22:00:00,Sunny/clear,18.1,1006.8,68.0,1.1,335.0
25836,4219879,fengtai_meo,2018-05-31 22:00:00,Sunny/clear,20.2,1007.8,65.0,0.6,304.0
25837,4219880,daxing_meo,2018-05-31 22:00:00,Sunny/clear,17.9,1009.6,72.0,0.0,999017.0
25838,4219881,fangshan_meo,2018-05-31 22:00:00,Sunny/clear,19.1,1008.5,57.0,1.0,309.0
25839,4219882,xiayunling_meo,2018-05-31 22:00:00,Sunny/clear,15.2,968.8,64.0,0.9,149.0
25840,4221398,shunyi_meo,2018-05-31 23:00:00,Sunny/clear,22.6,1011.2,46.0,1.8,353.0
25841,4221399,hadian_meo,2018-05-31 23:00:00,Sunny/clear,21.1,1009.1,55.0,1.0,59.0
25842,4221400,yanqing_meo,2018-05-31 23:00:00,Sunny/clear,18.4,960.4,54.0,0.4,23.0
25843,4221401,miyun_meo,2018-05-31 23:00:00,Sunny/clear,21.5,1006.4,56.0,0.7,102.0
25844,4221402,huairou_meo,2018-05-31 23:00:00,Sunny/clear,20.3,1005.9,63.0,0.4,293.0
25845,4221403,shangdianzi_meo,2018-05-31 23:00:00,Sunny/clear,20.1,981.4,45.0,2.7,60.0
25846,4221404,pinggu_meo,2018-05-31 23:00:00,Sunny/clear,20.6,1010.6,54.0,0.9,334.0
25847,4221405,tongzhou_meo,2018-05-31 23:00:00,Sunny/clear,21.4,1012.1,64.0,1.1,316.0
25848,4221406,chaoyang_meo,2018-05-31 23:00:00,Sunny/clear,24.1,1010.6,43.0,1.2,60.0
25849,4221407,pingchang_meo,2018-05-31 23:00:00,Sunny/clear,22.9,1005.9,42.0,0.8,343.0
25850,4221408,zhaitang_meo,2018-05-31 23:00:00,Sunny/clear,17.2,965.7,55.0,0.4,4.0
25851,4221409,mentougou_meo,2018-05-31 23:00:00,Sunny/clear,23.3,1004.8,40.0,1.5,301.0
25852,4221410,beijing_meo,2018-05-31 23:00:00,Sunny/clear,24.6,1010.7,39.0,1.7,34.0
25853,4221411,shijingshan_meo,2018-05-31 23:00:00,Sunny/clear,23.8,1007.2,52.0,0.6,351.0
25854,4221412,fengtai_meo,2018-05-31 23:00:00,Sunny/clear,25.1,1008.2,40.0,1.6,60.0
25855,4221413,daxing_meo,2018-05-31 23:00:00,Sunny/clear,24.2,1010.0,48.0,0.5,18.0
25856,4221414,fangshan_meo,2018-05-31 23:00:00,Sunny/clear,22.9,1008.9,48.0,0.6,313.0
25857,4221415,xiayunling_meo,2018-05-31 23:00:00,Sunny/clear,18.6,969.0,55.0,2.0,139.0

In [69]:
def weather_mode(seq):
    seq=list(seq)
    seq_class=np.unique(seq)
    freq=np.zeros(len(seq_class))
    for i in range(len(seq_class)):
        freq[i]=seq.count(seq_class[i])
    return(seq_class[np.argmax(freq)])

def uniq_aggr(df_me):
    # set outliers of variables as nan
    df_me['temperature']=df_me['temperature'].apply(lambda x: np.nan if x>=999999 else x)
    df_me['pressure']=df_me['pressure'].apply(lambda x: np.nan if x>=999999 else x)
    df_me['wind_speed']=df_me['wind_speed'].apply(lambda x: np.nan if x>=999999 else x)
    df_me['wind_direction']=df_me['wind_direction'].apply(lambda x: np.nan if x>=999999 else x)
    df_me['humidity']=df_me['humidity'].apply(lambda x: np.nan if x>=999999 else x)

    #  time steps
    time_me,ind_me=np.unique(df_me['utc_time'],return_inverse=True)

    # aggregate the results
    temperature,pressure,humidity,wind_direction,wind_speed,weather=list(),list(),list(),list(),list(),list()
    for i in range(len(time_me)):
        temperature.append(np.nanmedian(df_me[ind_me==i]['temperature']))
        pressure.append(np.nanmedian(df_me[ind_me==i]['pressure']))
        humidity.append(np.nanmedian(df_me[ind_me==i]['humidity']))
        wind_direction.append(np.nanmedian(df_me[ind_me==i]['wind_direction']))
        wind_speed.append(np.nanmedian(df_me[ind_me==i]['wind_speed']))
        weather.append(weather_mode(df_me[ind_me==i]['weather']))

    # create new df
    df1_me=pd.DataFrame({
        'utc_time':time_me,
        'temperature':temperature,
        'pressure':pressure,
        'humidity':humidity,
        'wind_direction':wind_direction,
        'wind_speed':wind_speed,
        'weather':weather
    })
    
    return df1_me

In [70]:
df1_me_p1=uniq_aggr(df0_me_p1)
df1_me_p2=uniq_aggr(df0_me_p2)

In [71]:
# df1_me_p1.describe()
df1_me_p2.describe()

          humidity     pressure  temperature  wind_direction   wind_speed
count  1445.000000  1445.000000  1445.000000     1445.000000  1445.000000
mean     50.821799  1004.601107    18.230519      867.583391     1.980104
std      23.210554     6.877920     6.770502    26276.283354     1.147274
min       9.000000   971.900000     0.200000       32.500000     0.000000
25%      30.000000   999.900000    13.900000      121.000000     1.100000
50%      50.000000  1004.500000    18.700000      185.000000     1.600000
75%      69.000000  1009.600000    23.050000      215.000000     2.600000
max      96.000000  1023.250000    34.650000   999017.000000     7.650000

In [74]:
#df1_me_p1
df1_me_p2.iloc[17:,:]

,humidity,pressure,temperature,utc_time,weather,wind_direction,wind_speed
17,45.5,1005.30,15.40,2018-04-01 01:00:00,Hail,96.0,1.25
18,45.5,1004.90,17.90,2018-04-01 02:00:00,Hail,134.5,1.70
19,40.0,1004.15,20.45,2018-04-01 03:00:00,Hail,181.0,1.70
20,35.0,1002.95,22.50,2018-04-01 04:00:00,Hail,204.0,3.30
21,32.0,1001.40,24.00,2018-04-01 05:00:00,Hail,190.5,3.65
22,27.5,999.95,25.20,2018-04-01 06:00:00,Hail,194.0,3.60
23,22.5,999.10,26.25,2018-04-01 07:00:00,Hail,201.5,3.45
24,22.0,998.15,26.25,2018-04-01 08:00:00,Hail,194.5,3.10
25,21.5,998.20,26.05,2018-04-01 09:00:00,Hail,191.5,2.95
26,24.0,997.90,24.60,2018-04-01 10:00:00,Hail,196.5,1.75
27,29.0,998.30,23.00,2018-04-01 11:00:00,Hail,191.0,1.70
28,37.0,998.70,21.10,2018-04-01 12:00:00,Hail,198.5,1.40
29,43.0,999.05,19.35,2018-04-01 13:00:00,Hail,179.0,1.20
30,45.0,998.40,18.70,2018-04-01 14:00:00,Hail,213.0,1.60
31,45.5,998.75,17.10,2018-04-01 15:00:00,Hail,192.5,1.40
32,49.0,998.75,15.95,2018-04-01 16:00:00,Hail,140.0,1.25
33,55.0,998.35,14.75,2018-04-01 17:00:00,Hail,140.5,1.00
34,58.0,998.20,14.05,2018-04-01 18:00:00,Hail,116.0,1.10
35,61.0,998.10,13.55,2018-04-01 19:00:00,Hail,100.0,1.05
36,70.5,997.75,12.70,2018-04-01 20:00:00,Hail,215.0,0.80
37,74.5,997.90,12.50,2018-04-01 21:00:00,Hail,136.5,1.10
38,77.5,998.25,12.05,2018-04-01 22:00:00,Hail,81.0,1.15
39,83.5,998.75,12.55,2018-04-01 23:00:00,Hail,123.0,1.20
40,69.0,999.15,16.45,2018-04-02 01:00:00,Hail,81.0,1.40
41,64.5,999.15,18.45,2018-04-02 02:00:00,Hail,82.0,1.65
42,61.5,999.00,20.00,2018-04-02 03:00:00,Hail,108.5,2.10
43,57.5,998.40,21.35,2018-04-02 04:00:00,Hail,110.5,1.90
44,50.0,997.75,22.80,2018-04-02 05:00:00,Hail,110.0,2.20
45,45.0,997.35,24.10,2018-04-02 06:00:00,Hail,151.5,2.15
46,45.0,996.75,24.60,2018-04-02 07:00:00,Hail,133.0,2.05
...,...,...,...,...,...,...,...
1415,53.5,1005.85,18.55,2018-05-30 18:00:00,Sunny/clear,92.5,1.35
1416,57.5,1006.55,18.40,2018-05-30 19:00:00,Sunny/clear,66.5,1.00
1417,61.0,1006.95,17.50,2018-05-30 20:00:00,Sunny/clear,62.5,1.40
1418,67.0,1007.45,16.00,2018-05-30 21:00:00,Sunny/clear,134.5,1.00
1419,62.5,1007.95,18.55,2018-05-30 22:00:00,Sunny/clear,60.5,1.15
1420,52.0,1008.25,21.00,2018-05-30 23:00:00,Sunny/clear,59.0,1.55
1421,42.5,1008.50,23.60,2018-05-31 00:00:00,Sunny/clear,65.0,1.50
1422,37.0,1008.50,26.20,2018-05-31 01:00:00,Sunny/clear,79.0,1.60
1423,31.5,1008.50,28.30,2018-05-31 02:00:00,Sunny/clear,90.5,1.40
1424,26.5,1008.20,30.50,2018-05-31 03:00:00,Sunny/clear,131.0,1.20
1425,23.0,1007.70,32.20,2018-05-31 04:00:00,Sunny/clear,216.5,1.70
1426,20.0,1006.75,33.35,2018-05-31 05:00:00,Sunny/clear,199.0,1.90
1427,16.5,1005.95,34.15,2018-05-31 06:00:00,Sunny/clear,218.5,2.35
1428,16.0,1005.30,34.55,2018-05-31 07:00:00,Sunny/clear,201.5,2.50
1429,17.0,1004.95,34.65,2018-05-31 08:00:00,Sunny/clear,203.0,2.70
1430,16.0,1004.65,34.15,2018-05-31 09:00:00,Sunny/clear,195.5,3.10
1431,17.5,1004.90,33.45,2018-05-31 10:00:00,Sunny/clear,194.5,3.05
1432,22.0,1005.15,31.60,2018-05-31 11:00:00,Sunny/clear,199.0,2.05
1433,27.0,1005.60,27.85,2018-05-31 12:00:00,Sunny/clear,214.0,1.55
1434,31.0,1006.30,27.00,2018-05-31 13:00:00,Sunny/clear,213.5,1.45
1435,35.0,1006.65,24.70,2018-05-31 14:00:00,Sunny/clear,211.5,1.35
1436,40.0,1006.60,23.05,2018-05-31 15:00:00,Sunny/clear,253.5,0.95
1437,48.0,1006.50,20.90,2018-05-31 16:00:00,Sunny/clear,235.5,1.20
1438,53.5,1006.65,19.70,2018-05-31 17:00:00,Sunny/clear,296.5,0.70
1439,57.0,1006.65,18.55,2018-05-31 18:00:00,Sunny/clear,233.0,0.85
1440,59.0,1006.70,17.55,2018-05-31 19:00:00,Sunny/clear,245.0,0.55
1441,63.5,1006.75,16.60,2018-05-31 20:00:00,Sunny/clear,132.5,0.80
1442,67.0,1006.95,16.55,2018-05-31 21:00:00,Sunny/clear,200.0,0.65
1443,63.5,1007.30,18.15,2018-05-31 22:00:00,Sunny/clear,120.0,1.00
1444,50.0,1007.70,22.05,2018-05-31 23:00:00,Sunny/clear,120.5,0.95

In [75]:
df1_me=df1_me_p1.append(df1_me_p2.iloc[17:,:], ignore_index=True)
df1_me

,humidity,pressure,temperature,utc_time,weather,wind_direction,wind_speed
0,38.0,1020.35,-6.40,2018-01-31 16:00:00,Sunny/clear,175.5,0.90
1,39.0,1020.05,-6.80,2018-01-31 17:00:00,Sunny/clear,288.0,0.55
2,42.0,1019.65,-7.45,2018-01-31 18:00:00,Sunny/clear,118.5,0.95
3,43.5,1019.35,-8.05,2018-01-31 19:00:00,Sunny/clear,145.0,0.80
4,44.5,1018.90,-8.65,2018-01-31 20:00:00,Sunny/clear,284.5,1.05
5,45.0,1019.05,-9.25,2018-01-31 21:00:00,Sunny/clear,159.0,1.00
6,46.0,1019.25,-9.60,2018-01-31 22:00:00,Sunny/clear,103.0,0.95
7,47.5,1019.85,-9.70,2018-01-31 23:00:00,Sunny/clear,211.0,0.80
8,47.5,1020.50,-9.55,2018-02-01 00:00:00,Sunny/clear,252.0,0.90
9,41.0,1020.85,-5.55,2018-02-01 01:00:00,Sunny/clear,255.5,0.80
10,27.5,1020.95,-1.95,2018-02-01 02:00:00,Sunny/clear,82.5,1.30
11,21.5,1020.70,0.45,2018-02-01 03:00:00,Sunny/clear,76.0,1.45
12,18.0,1020.00,2.75,2018-02-01 04:00:00,Sunny/clear,122.0,1.90
13,18.0,1019.20,3.55,2018-02-01 05:00:00,Sunny/clear,151.0,2.05
14,16.0,1018.90,4.20,2018-02-01 06:00:00,Sunny/clear,225.0,2.70
15,15.5,1018.95,4.45,2018-02-01 07:00:00,Sunny/clear,270.0,2.50
16,16.0,1019.25,4.00,2018-02-01 08:00:00,Sunny/clear,301.0,2.20
17,18.5,1020.30,3.10,2018-02-01 09:00:00,Sunny/clear,308.0,2.70
18,22.0,1021.90,1.85,2018-02-01 10:00:00,Sunny/clear,316.0,3.50
19,23.0,1023.15,1.40,2018-02-01 11:00:00,Sunny/clear,309.0,3.85
20,21.0,1024.25,0.80,2018-02-01 12:00:00,Sunny/clear,319.5,3.60
21,21.0,1025.25,-0.05,2018-02-01 13:00:00,Sunny/clear,336.0,4.25
22,21.0,1026.30,-1.05,2018-02-01 14:00:00,Sunny/clear,327.5,4.15
23,22.0,1027.15,-2.15,2018-02-01 15:00:00,Sunny/clear,328.5,4.35
24,24.0,1028.30,-3.20,2018-02-01 16:00:00,Sunny/clear,320.0,4.00
25,26.0,1028.75,-3.90,2018-02-01 17:00:00,Sunny/clear,325.0,4.00
26,27.5,1029.25,-4.40,2018-02-01 18:00:00,Sunny/clear,308.5,4.25
27,28.0,1029.50,-4.65,2018-02-01 19:00:00,Sunny/clear,321.5,3.45
28,29.0,1029.90,-5.40,2018-02-01 20:00:00,Sunny/clear,322.5,3.20
29,27.0,1031.05,-5.70,2018-02-01 21:00:00,Sunny/clear,316.0,4.35
...,...,...,...,...,...,...,...
2823,53.5,1005.85,18.55,2018-05-30 18:00:00,Sunny/clear,92.5,1.35
2824,57.5,1006.55,18.40,2018-05-30 19:00:00,Sunny/clear,66.5,1.00
2825,61.0,1006.95,17.50,2018-05-30 20:00:00,Sunny/clear,62.5,1.40
2826,67.0,1007.45,16.00,2018-05-30 21:00:00,Sunny/clear,134.5,1.00
2827,62.5,1007.95,18.55,2018-05-30 22:00:00,Sunny/clear,60.5,1.15
2828,52.0,1008.25,21.00,2018-05-30 23:00:00,Sunny/clear,59.0,1.55
2829,42.5,1008.50,23.60,2018-05-31 00:00:00,Sunny/clear,65.0,1.50
2830,37.0,1008.50,26.20,2018-05-31 01:00:00,Sunny/clear,79.0,1.60
2831,31.5,1008.50,28.30,2018-05-31 02:00:00,Sunny/clear,90.5,1.40
2832,26.5,1008.20,30.50,2018-05-31 03:00:00,Sunny/clear,131.0,1.20
2833,23.0,1007.70,32.20,2018-05-31 04:00:00,Sunny/clear,216.5,1.70
2834,20.0,1006.75,33.35,2018-05-31 05:00:00,Sunny/clear,199.0,1.90
2835,16.5,1005.95,34.15,2018-05-31 06:00:00,Sunny/clear,218.5,2.35
2836,16.0,1005.30,34.55,2018-05-31 07:00:00,Sunny/clear,201.5,2.50
2837,17.0,1004.95,34.65,2018-05-31 08:00:00,Sunny/clear,203.0,2.70
2838,16.0,1004.65,34.15,2018-05-31 09:00:00,Sunny/clear,195.5,3.10
2839,17.5,1004.90,33.45,2018-05-31 10:00:00,Sunny/clear,194.5,3.05
2840,22.0,1005.15,31.60,2018-05-31 11:00:00,Sunny/clear,199.0,2.05
2841,27.0,1005.60,27.85,2018-05-31 12:00:00,Sunny/clear,214.0,1.55
2842,31.0,1006.30,27.00,2018-05-31 13:00:00,Sunny/clear,213.5,1.45
2843,35.0,1006.65,24.70,2018-05-31 14:00:00,Sunny/clear,211.5,1.35
2844,40.0,1006.60,23.05,2018-05-31 15:00:00,Sunny/clear,253.5,0.95
2845,48.0,1006.50,20.90,2018-05-31 16:00:00,Sunny/clear,235.5,1.20
2846,53.5,1006.65,19.70,2018-05-31 17:00:00,Sunny/clear,296.5,0.70
2847,57.0,1006.65,18.55,2018-05-31 18:00:00,Sunny/clear,233.0,0.85
2848,59.0,1006.70,17.55,2018-05-31 19:00:00,Sunny/clear,245.0,0.55
2849,63.5,1006.75,16.60,2018-05-31 20:00:00,Sunny/clear,132.5,0.80
2850,67.0,1006.95,16.55,2018-05-31 21:00:00,Sunny/clear,200.0,0.65
2851,63.5,1007.30,18.15,2018-05-31 22:00:00,Sunny/clear,120.0,1.00
2852,50.0,1007.70,22.05,2018-05-31 23:00:00,Sunny/clear,120.5,0.95

# Data Merge

In [76]:
# data merge
left=df1_aq
right=df1_me
df_merge=pd.merge(left, right, how='right', on='utc_time')
df_merge=df_merge.sort_values(by='utc_time',ascending=True)
df_merge.index=np.arange(0,len(df1_me['utc_time']))

In [77]:
df_merge

,PM2.5,utc_time,humidity,pressure,temperature,weather,wind_direction,wind_speed
0,50.840000,2018-01-31 16:00:00,38.0,1020.35,-6.40,Sunny/clear,175.5,0.90
1,47.823529,2018-01-31 17:00:00,39.0,1020.05,-6.80,Sunny/clear,288.0,0.55
2,47.235294,2018-01-31 18:00:00,42.0,1019.65,-7.45,Sunny/clear,118.5,0.95
3,46.411765,2018-01-31 19:00:00,43.5,1019.35,-8.05,Sunny/clear,145.0,0.80
4,44.764706,2018-01-31 20:00:00,44.5,1018.90,-8.65,Sunny/clear,284.5,1.05
5,42.160000,2018-01-31 21:00:00,45.0,1019.05,-9.25,Sunny/clear,159.0,1.00
6,39.240000,2018-01-31 22:00:00,46.0,1019.25,-9.60,Sunny/clear,103.0,0.95
7,40.970588,2018-01-31 23:00:00,47.5,1019.85,-9.70,Sunny/clear,211.0,0.80
8,40.600000,2018-02-01 00:00:00,47.5,1020.50,-9.55,Sunny/clear,252.0,0.90
9,46.117647,2018-02-01 01:00:00,41.0,1020.85,-5.55,Sunny/clear,255.5,0.80
10,48.727273,2018-02-01 02:00:00,27.5,1020.95,-1.95,Sunny/clear,82.5,1.30
11,48.264706,2018-02-01 03:00:00,21.5,1020.70,0.45,Sunny/clear,76.0,1.45
12,45.029412,2018-02-01 04:00:00,18.0,1020.00,2.75,Sunny/clear,122.0,1.90
13,40.781250,2018-02-01 05:00:00,18.0,1019.20,3.55,Sunny/clear,151.0,2.05
14,37.272727,2018-02-01 06:00:00,16.0,1018.90,4.20,Sunny/clear,225.0,2.70
15,36.941176,2018-02-01 07:00:00,15.5,1018.95,4.45,Sunny/clear,270.0,2.50
16,33.529412,2018-02-01 08:00:00,16.0,1019.25,4.00,Sunny/clear,301.0,2.20
17,30.823529,2018-02-01 09:00:00,18.5,1020.30,3.10,Sunny/clear,308.0,2.70
18,29.090909,2018-02-01 10:00:00,22.0,1021.90,1.85,Sunny/clear,316.0,3.50
19,23.240000,2018-02-01 11:00:00,23.0,1023.15,1.40,Sunny/clear,309.0,3.85
20,15.558824,2018-02-01 12:00:00,21.0,1024.25,0.80,Sunny/clear,319.5,3.60
21,9.484848,2018-02-01 13:00:00,21.0,1025.25,-0.05,Sunny/clear,336.0,4.25
22,7.000000,2018-02-01 14:00:00,21.0,1026.30,-1.05,Sunny/clear,327.5,4.15
23,6.200000,2018-02-01 15:00:00,22.0,1027.15,-2.15,Sunny/clear,328.5,4.35
24,5.960000,2018-02-01 16:00:00,24.0,1028.30,-3.20,Sunny/clear,320.0,4.00
25,6.794118,2018-02-01 17:00:00,26.0,1028.75,-3.90,Sunny/clear,325.0,4.00
26,6.200000,2018-02-01 18:00:00,27.5,1029.25,-4.40,Sunny/clear,308.5,4.25
27,6.480000,2018-02-01 19:00:00,28.0,1029.50,-4.65,Sunny/clear,321.5,3.45
28,6.840000,2018-02-01 20:00:00,29.0,1029.90,-5.40,Sunny/clear,322.5,3.20
29,6.818182,2018-02-01 21:00:00,27.0,1031.05,-5.70,Sunny/clear,316.0,4.35
...,...,...,...,...,...,...,...,...
2823,28.848485,2018-05-30 18:00:00,53.5,1005.85,18.55,Sunny/clear,92.5,1.35
2824,31.147059,2018-05-30 19:00:00,57.5,1006.55,18.40,Sunny/clear,66.5,1.00
2825,32.470588,2018-05-30 20:00:00,61.0,1006.95,17.50,Sunny/clear,62.5,1.40
2826,37.823529,2018-05-30 21:00:00,67.0,1007.45,16.00,Sunny/clear,134.5,1.00
2827,41.088235,2018-05-30 22:00:00,62.5,1007.95,18.55,Sunny/clear,60.5,1.15
2828,44.441176,2018-05-30 23:00:00,52.0,1008.25,21.00,Sunny/clear,59.0,1.55
2829,47.294118,2018-05-31 00:00:00,42.5,1008.50,23.60,Sunny/clear,65.0,1.50
2830,45.852941,2018-05-31 01:00:00,37.0,1008.50,26.20,Sunny/clear,79.0,1.60
2831,39.205882,2018-05-31 02:00:00,31.5,1008.50,28.30,Sunny/clear,90.5,1.40
2832,37.781250,2018-05-31 03:00:00,26.5,1008.20,30.50,Sunny/clear,131.0,1.20
2833,33.090909,2018-05-31 04:00:00,23.0,1007.70,32.20,Sunny/clear,216.5,1.70
2834,27.937500,2018-05-31 05:00:00,20.0,1006.75,33.35,Sunny/clear,199.0,1.90
2835,22.000000,2018-05-31 06:00:00,16.5,1005.95,34.15,Sunny/clear,218.5,2.35
2836,19.878788,2018-05-31 07:00:00,16.0,1005.30,34.55,Sunny/clear,201.5,2.50
2837,20.666667,2018-05-31 08:00:00,17.0,1004.95,34.65,Sunny/clear,203.0,2.70
2838,21.235294,2018-05-31 09:00:00,16.0,1004.65,34.15,Sunny/clear,195.5,3.10
2839,19.352941,2018-05-31 10:00:00,17.5,1004.90,33.45,Sunny/clear,194.5,3.05
2840,21.882353,2018-05-31 11:00:00,22.0,1005.15,31.60,Sunny/clear,199.0,2.05
2841,23.558824,2018-05-31 12:00:00,27.0,1005.60,27.85,Sunny/clear,214.0,1.55
2842,25.125000,2018-05-31 13:00:00,31.0,1006.30,27.00,Sunny/clear,213.5,1.45
2843,30.029412,2018-05-31 14:00:00,35.0,1006.65,24.70,Sunny/clear,211.5,1.35
2844,30.294118,2018-05-31 15:00:00,40.0,1006.60,23.05,Sunny/clear,253.5,0.95
2845,27.882353,2018-05-31 16:00:00,48.0,1006.50,20.90,Sunny/clear,235.5,1.20
2846,29.470588,2018-05-31 17:00:00,53.5,1006.65,19.70,Sunny/clear,296.5,0.70
2847,29.176471,2018-05-31 18:00:00,57.0,1006.65,18.55,Sunny/clear,233.0,0.85
2848,30.882353,2018-05-31 19:00:00,59.0,1006.70,17.55,Sunny/clear,245.0,0.55
2849,32.000000,2018-05-31 20:00:00,63.5,1006.75,16.60,Sunny/clear,132.5,0.80
2850,32.264706,2018-05-31 21:00:00,67.0,1006.95,16.55,Sunny/clear,200.0,0.65
2851,33.058824,2018-05-31 22:00:00,63.5,1007.30,18.15,Sunny/clear,120.0,1.00
2852,33.676471,2018-05-31 23:00:00,50.0,1007.70,22.05,Sunny/clear,120.5,0.95

In [78]:
np.sum(df_merge.isna())

PM2.5             93
utc_time           0
humidity           0
pressure           0
temperature        0
weather            0
wind_direction     0
wind_speed         0
dtype: int64