In [1]:
# import
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# set data directory
root_dir=os.getcwd()+'/'
dir_17_aq=root_dir+'beijing_17_18_aq.csv'
dir_17_me=root_dir+'beijing_17_18_meo.csv'

# load data by pandas
df_aq=pd.read_csv(dir_17_aq)
df_me=pd.read_csv(dir_17_me)

# Air Quality Data Preprocess

In [3]:
print('The number of data is',len(df_aq['O3']))
df_aq

The number of data is 311010

,stationId,utc_time,PM2.5,PM10,NO2,CO,O3,SO2
0,aotizhongxin_aq,2017-01-01 14:00:00,453.0,467.0,156.0,7.2,3.0,9.0
1,aotizhongxin_aq,2017-01-01 15:00:00,417.0,443.0,143.0,6.8,2.0,8.0
2,aotizhongxin_aq,2017-01-01 16:00:00,395.0,467.0,141.0,6.9,3.0,8.0
3,aotizhongxin_aq,2017-01-01 17:00:00,420.0,484.0,139.0,7.4,3.0,9.0
4,aotizhongxin_aq,2017-01-01 18:00:00,453.0,520.0,157.0,7.6,4.0,9.0
5,aotizhongxin_aq,2017-01-01 19:00:00,429.0,NaN,141.0,6.5,3.0,9.0
6,aotizhongxin_aq,2017-01-01 20:00:00,211.0,NaN,110.0,3.3,NaN,11.0
7,aotizhongxin_aq,2017-01-01 21:00:00,116.0,NaN,87.0,2.2,4.0,13.0
8,aotizhongxin_aq,2017-01-01 22:00:00,51.0,NaN,58.0,1.3,26.0,14.0
9,aotizhongxin_aq,2017-01-01 23:00:00,38.0,NaN,55.0,1.1,28.0,14.0
10,aotizhongxin_aq,2017-01-02 00:00:00,21.0,NaN,40.0,0.7,42.0,16.0
11,aotizhongxin_aq,2017-01-02 01:00:00,16.0,NaN,40.0,0.8,44.0,18.0
12,aotizhongxin_aq,2017-01-02 02:00:00,23.0,NaN,42.0,0.7,45.0,17.0
13,aotizhongxin_aq,2017-01-02 03:00:00,18.0,NaN,30.0,0.6,59.0,14.0
14,aotizhongxin_aq,2017-01-02 04:00:00,58.0,247.0,76.0,2.4,46.0,12.0
15,aotizhongxin_aq,2017-01-02 05:00:00,176.0,NaN,99.0,0.3,42.0,17.0
16,aotizhongxin_aq,2017-01-02 06:00:00,109.0,211.0,86.0,2.6,58.0,14.0
17,aotizhongxin_aq,2017-01-02 07:00:00,267.0,NaN,125.0,4.2,53.0,19.0
18,aotizhongxin_aq,2017-01-02 08:00:00,260.0,NaN,115.0,3.9,56.0,18.0
19,aotizhongxin_aq,2017-01-02 09:00:00,212.0,NaN,112.0,3.6,50.0,14.0
20,aotizhongxin_aq,2017-01-02 10:00:00,183.0,NaN,111.0,0.3,33.0,14.0
21,aotizhongxin_aq,2017-01-02 11:00:00,136.0,NaN,89.0,2.3,41.0,14.0
22,aotizhongxin_aq,2017-01-02 12:00:00,137.0,NaN,89.0,2.2,35.0,13.0
23,aotizhongxin_aq,2017-01-02 13:00:00,125.0,NaN,90.0,2.1,28.0,13.0
24,aotizhongxin_aq,2017-01-02 14:00:00,153.0,NaN,108.0,2.5,13.0,14.0
25,aotizhongxin_aq,2017-01-02 15:00:00,165.0,NaN,126.0,3.1,2.0,14.0
26,aotizhongxin_aq,2017-01-02 16:00:00,225.0,NaN,148.0,4.9,4.0,23.0
27,aotizhongxin_aq,2017-01-02 17:00:00,275.0,NaN,158.0,6.4,7.0,28.0
28,aotizhongxin_aq,2017-01-02 18:00:00,293.0,NaN,155.0,6.4,5.0,17.0
29,aotizhongxin_aq,2017-01-02 19:00:00,293.0,NaN,153.0,6.2,5.0,16.0
...,...,...,...,...,...,...,...,...
310980,zhiwuyuan_aq,2018-01-30 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310981,zhiwuyuan_aq,2018-01-30 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310982,zhiwuyuan_aq,2018-01-30 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310983,zhiwuyuan_aq,2018-01-30 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310984,zhiwuyuan_aq,2018-01-30 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310985,zhiwuyuan_aq,2018-01-30 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310986,zhiwuyuan_aq,2018-01-30 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310987,zhiwuyuan_aq,2018-01-30 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310988,zhiwuyuan_aq,2018-01-30 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310989,zhiwuyuan_aq,2018-01-30 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310990,zhiwuyuan_aq,2018-01-30 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310991,zhiwuyuan_aq,2018-01-30 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310992,zhiwuyuan_aq,2018-01-30 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310993,zhiwuyuan_aq,2018-01-30 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310994,zhiwuyuan_aq,2018-01-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310995,zhiwuyuan_aq,2018-01-31 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310996,zhiwuyuan_aq,2018-01-31 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310997,zhiwuyuan_aq,2018-01-31 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310998,zhiwuyuan_aq,2018-01-31 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN
310999,zhiwuyuan_aq,2018-01-31 05:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311000,zhiwuyuan_aq,2018-01-31 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311001,zhiwuyuan_aq,2018-01-31 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311002,zhiwuyuan_aq,2018-01-31 08:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311003,zhiwuyuan_aq,2018-01-31 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311004,zhiwuyuan_aq,2018-01-31 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311005,zhiwuyuan_aq,2018-01-31 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311006,zhiwuyuan_aq,2018-01-31 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311007,zhiwuyuan_aq,2018-01-31 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311008,zhiwuyuan_aq,2018-01-31 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN
311009,zhiwuyuan_aq,2018-01-31 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_aq.describe()

,PM2.5,PM10,NO2,CO,O3,SO2
count,290621.000000,227747.000000,292359.000000,268197.000000,290589.000000,292462.000000
mean,58.785570,88.059259,45.792457,0.960677,55.692755,8.981003
std,66.113851,89.292875,32.065045,1.001856,53.821424,11.702594
min,2.000000,5.000000,1.000000,0.100000,1.000000,1.000000
25%,16.000000,37.000000,20.000000,0.400000,12.000000,2.000000
50%,39.000000,70.000000,39.000000,0.700000,45.000000,5.000000
75%,77.000000,113.000000,66.000000,1.200000,79.000000,11.000000
max,1004.000000,3000.000000,300.000000,15.000000,504.000000,307.000000

In [5]:
# print time steps
time_aq,ind_aq=np.unique(df_aq['utc_time'],return_inverse=True)
print('There are',len(time_aq),'time steps in total')
print(time_aq)
print(ind_aq)

There are 8701 time steps in total
['2017-01-01 14:00:00' '2017-01-01 15:00:00' '2017-01-01 16:00:00' ...
 '2018-01-31 13:00:00' '2018-01-31 14:00:00' '2018-01-31 15:00:00']
[   0    1    2 ... 8698 8699 8700]

In [6]:
# average over all stations
pollution=np.zeros(len(time_aq))
for i in range(len(time_aq)):
    pollution[i]=np.nanmean(df_aq[ind_aq==i]['PM2.5'])
# create new df
df1_aq=pd.DataFrame({
    'utc_time':time_aq,
    'PM2.5':pollution
})
df1_aq

/Users/zhanght/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: Mean of empty slice
  after removing the cwd from sys.path.

           PM2.5             utc_time
0     402.600000  2017-01-01 14:00:00
1     400.428571  2017-01-01 15:00:00
2     393.400000  2017-01-01 16:00:00
3     379.314286  2017-01-01 17:00:00
4     346.323529  2017-01-01 18:00:00
5     313.971429  2017-01-01 19:00:00
6     259.114286  2017-01-01 20:00:00
7     207.628571  2017-01-01 21:00:00
8     155.685714  2017-01-01 22:00:00
9     124.285714  2017-01-01 23:00:00
10    122.628571  2017-01-02 00:00:00
11    124.485714  2017-01-02 01:00:00
12    135.600000  2017-01-02 02:00:00
13    164.457143  2017-01-02 03:00:00
14    200.600000  2017-01-02 04:00:00
15    214.542857  2017-01-02 05:00:00
16    187.771429  2017-01-02 06:00:00
17    211.285714  2017-01-02 07:00:00
18    221.911765  2017-01-02 08:00:00
19    220.800000  2017-01-02 09:00:00
20    206.200000  2017-01-02 10:00:00
21    213.600000  2017-01-02 11:00:00
22    221.342857  2017-01-02 12:00:00
23    234.285714  2017-01-02 13:00:00
24    250.400000  2017-01-02 14:00:00
25    263.294118  2017-01-02 15:00:00
26    280.885714  2017-01-02 16:00:00
27    291.029412  2017-01-02 17:00:00
28    289.771429  2017-01-02 18:00:00
29    278.828571  2017-01-02 19:00:00
...          ...                  ...
8671   15.121212  2018-01-30 10:00:00
8672   19.941176  2018-01-30 11:00:00
8673   19.323529  2018-01-30 12:00:00
8674   15.235294  2018-01-30 13:00:00
8675   10.647059  2018-01-30 14:00:00
8676   10.363636  2018-01-30 15:00:00
8677    9.575758  2018-01-30 16:00:00
8678   10.382353  2018-01-30 17:00:00
8679    8.823529  2018-01-30 18:00:00
8680   10.645161  2018-01-30 19:00:00
8681   12.516129  2018-01-30 20:00:00
8682   11.766667  2018-01-30 21:00:00
8683   13.833333  2018-01-30 22:00:00
8684   14.500000  2018-01-30 23:00:00
8685   17.233333  2018-01-31 00:00:00
8686   20.333333  2018-01-31 01:00:00
8687   19.281250  2018-01-31 02:00:00
8688   18.387097  2018-01-31 03:00:00
8689   16.652174  2018-01-31 04:00:00
8690   14.906250  2018-01-31 05:00:00
8691   15.617647  2018-01-31 06:00:00
8692   17.764706  2018-01-31 07:00:00
8693   21.676471  2018-01-31 08:00:00
8694   24.588235  2018-01-31 09:00:00
8695   29.764706  2018-01-31 10:00:00
8696   33.363636  2018-01-31 11:00:00
8697   42.000000  2018-01-31 12:00:00
8698   46.176471  2018-01-31 13:00:00
8699   48.117647  2018-01-31 14:00:00
8700   48.558824  2018-01-31 15:00:00

[8701 rows x 2 columns]

In [7]:
# save the processed data
df1_aq.to_csv(root_dir+'aq_17.csv')

# Meteorological Data Preprocess

In [8]:
print('The number of data is',len(df_me['utc_time']))
df_me

The number of data is 158047

,station_id,longitude,latitude,utc_time,temperature,pressure,humidity,wind_direction,wind_speed,weather
0,shunyi_meo,116.615278,40.126667,2017-01-30 16:00:00,-1.7,1028.7,15,215.0,1.6,Sunny/clear
1,shunyi_meo,116.615278,40.126667,2017-01-30 17:00:00,-3.5,1028.4,24,16.0,1.0,Haze
2,shunyi_meo,116.615278,40.126667,2017-01-30 18:00:00,-3.7,1028.1,27,32.0,1.1,Haze
3,shunyi_meo,116.615278,40.126667,2017-01-30 19:00:00,-3.9,1027.6,27,21.0,0.9,Haze
4,shunyi_meo,116.615278,40.126667,2017-01-30 20:00:00,-4.1,1026.7,26,17.0,1.1,Haze
5,shunyi_meo,116.615278,40.126667,2017-01-30 21:00:00,-4.2,1026.1,28,68.0,0.9,Haze
6,shunyi_meo,116.615278,40.126667,2017-01-30 22:00:00,-4.0,1025.7,27,329.0,1.1,Haze
7,shunyi_meo,116.615278,40.126667,2017-01-30 23:00:00,-4.7,1025.9,29,28.0,0.7,Haze
8,shunyi_meo,116.615278,40.126667,2017-01-31 00:00:00,-4.9,1026.1,28,17.0,1.2,Haze
9,shunyi_meo,116.615278,40.126667,2017-01-31 01:00:00,-3.6,1026.2,28,29.0,1.1,Haze
10,shunyi_meo,116.615278,40.126667,2017-01-31 02:00:00,-1.7,1025.8,20,73.0,1.2,Haze
11,shunyi_meo,116.615278,40.126667,2017-01-31 03:00:00,0.4,1025.7,16,236.0,0.5,Haze
12,shunyi_meo,116.615278,40.126667,2017-01-31 04:00:00,1.5,1024.8,15,93.0,0.9,Haze
13,shunyi_meo,116.615278,40.126667,2017-01-31 05:00:00,3.4,1023.3,13,182.0,1.3,Sunny/clear
14,shunyi_meo,116.615278,40.126667,2017-01-31 06:00:00,4.7,1022.4,12,255.0,1.6,Sunny/clear
15,shunyi_meo,116.615278,40.126667,2017-01-31 07:00:00,5.7,1021.8,11,301.0,2.0,Sunny/clear
16,shunyi_meo,116.615278,40.126667,2017-01-31 08:00:00,5.7,1022.1,11,311.0,1.9,Sunny/clear
17,shunyi_meo,116.615278,40.126667,2017-01-31 09:00:00,3.8,1023.1,14,55.0,1.7,Sunny/clear
18,shunyi_meo,116.615278,40.126667,2017-01-31 10:00:00,0.4,1024.0,19,292.0,0.5,Haze
19,shunyi_meo,116.615278,40.126667,2017-01-31 11:00:00,-2.2,1024.9,34,999017.0,0.2,Haze
20,shunyi_meo,116.615278,40.126667,2017-01-31 12:00:00,-2.1,1025.9,28,37.0,1.7,Haze
21,shunyi_meo,116.615278,40.126667,2017-01-31 13:00:00,-1.3,1027.0,23,4.0,1.6,Haze
22,shunyi_meo,116.615278,40.126667,2017-01-31 14:00:00,-3.0,1028.2,28,15.0,1.1,Haze
23,shunyi_meo,116.615278,40.126667,2017-01-31 15:00:00,-4.1,1029.5,36,59.0,0.4,Haze
24,shunyi_meo,116.615278,40.126667,2017-01-31 16:00:00,-4.1,1030.4,29,289.0,0.8,Haze
25,shunyi_meo,116.615278,40.126667,2017-01-31 17:00:00,-3.6,1031.1,27,13.0,1.5,Sunny/clear
26,shunyi_meo,116.615278,40.126667,2017-01-31 18:00:00,-4.7,1031.9,30,17.0,0.9,Sunny/clear
27,shunyi_meo,116.615278,40.126667,2017-01-31 19:00:00,-5.8,1032.6,35,31.0,1.3,Sunny/clear
28,shunyi_meo,116.615278,40.126667,2017-01-31 20:00:00,-5.6,1033.3,35,47.0,1.7,Sunny/clear
29,shunyi_meo,116.615278,40.126667,2017-01-31 21:00:00,-4.0,1034.0,26,45.0,2.4,Sunny/clear
...,...,...,...,...,...,...,...,...,...,...
158017,xiayunling_meo,115.740556,39.728611,2018-01-30 10:00:00,-2.4,975.0,22,36.0,1.1,Sunny/clear
158018,xiayunling_meo,115.740556,39.728611,2018-01-30 11:00:00,-3.2,975.5,24,252.0,1.5,Sunny/clear
158019,xiayunling_meo,115.740556,39.728611,2018-01-30 12:00:00,-4.8,976.7,30,204.0,1.8,Sunny/clear
158020,xiayunling_meo,115.740556,39.728611,2018-01-30 13:00:00,-6.0,977.5,33,141.0,1.0,Sunny/clear
158021,xiayunling_meo,115.740556,39.728611,2018-01-30 14:00:00,-7.3,978.3,37,214.0,0.9,Sunny/clear
158022,xiayunling_meo,115.740556,39.728611,2018-01-30 15:00:00,-7.9,978.7,41,134.0,0.8,Sunny/clear
158023,xiayunling_meo,115.740556,39.728611,2018-01-30 16:00:00,-8.3,979.2,40,300.0,0.9,Sunny/clear
158024,xiayunling_meo,115.740556,39.728611,2018-01-30 17:00:00,-7.7,979.7,37,63.0,0.7,Sunny/clear
158025,xiayunling_meo,115.740556,39.728611,2018-01-30 18:00:00,-7.9,979.9,38,204.0,1.2,Sunny/clear
158026,xiayunling_meo,115.740556,39.728611,2018-01-30 19:00:00,-8.1,979.4,39,195.0,1.2,Sunny/clear
158027,xiayunling_meo,115.740556,39.728611,2018-01-30 20:00:00,-8.8,979.1,41,165.0,1.0,Sunny/clear
158028,xiayunling_meo,115.740556,39.728611,2018-01-30 21:00:00,-10.2,979.4,45,999017.0,0.0,Sunny/clear
158029,xiayunling_meo,115.740556,39.728611,2018-01-30 22:00:00,-10.4,979.7,47,178.0,1.0,Sunny/clear
158030,xiayunling_meo,115.740556,39.728611,2018-01-30 23:00:00,-9.9,979.8,45,197.0,1.6,Sunny/clear
158031,xiayunling_meo,115.740556,39.728611,2018-01-31 00:00:00,-10.9,979.7,49,310.0,0.8,Sunny/clear
158032,xiayunling_meo,115.740556,39.728611,2018-01-31 01:00:00,-9.7,979.7,45,191.0,1.2,Sunny/clear
158033,xiayunling_meo,115.740556,39.728611,2018-01-31 02:00:00,-5.1,979.4,34,999017.0,0.0,Sunny/clear
158034,xiayunling_meo,115.740556,39.728611,2018-01-31 03:00:00,-0.1,978.8,20,140.0,1.2,Sunny/clear
158035,xiayunling_meo,115.740556,39.728611,2018-01-31 04:00:00,1.3,977.9,16,213.0,2.9,Sunny/clear
158036,xiayunling_meo,115.740556,39.728611,2018-01-31 05:00:00,1.5,977.1,16,194.0,3.4,Sunny/clear
158037,xiayunling_meo,115.740556,39.728611,2018-01-31 06:00:00,1.7,976.1,15,176.0,3.0,Sunny/clear
158038,xiayunling_meo,115.740556,39.728611,2018-01-31 07:00:00,2.4,975.5,15,172.0,2.2,Sunny/clear
158039,xiayunling_meo,115.740556,39.728611,2018-01-31 08:00:00,1.3,975.4,16,230.0,1.6,Sunny/clear
158040,xiayunling_meo,115.740556,39.728611,2018-01-31 09:00:00,-0.5,975.9,20,220.0,1.7,Sunny/clear
158041,xiayunling_meo,115.740556,39.728611,2018-01-31 10:00:00,-3.4,976.5,27,175.0,1.6,Sunny/clear
158042,xiayunling_meo,115.740556,39.728611,2018-01-31 11:00:00,-5.0,977.2,32,210.0,0.8,Sunny/clear
158043,xiayunling_meo,115.740556,39.728611,2018-01-31 12:00:00,-6.4,977.5,36,999017.0,0.0,Sunny/clear
158044,xiayunling_meo,115.740556,39.728611,2018-01-31 13:00:00,-6.8,977.8,39,182.0,1.3,Sunny/clear
158045,xiayunling_meo,115.740556,39.728611,2018-01-31 14:00:00,-7.1,977.7,39,170.0,1.5,Sunny/clear
158046,xiayunling_meo,115.740556,39.728611,2018-01-31 15:00:00,-7.4,977.4,39,137.0,1.0,Sunny/clear

In [9]:
# set outliers of wind direction as nan
df_me['wind_direction']=df_me['wind_direction'].apply(lambda x: np.nan if x>360 else x)
df_me.describe()

,longitude,latitude,temperature,pressure,humidity,wind_direction,wind_speed
count,158047.000000,158047.000000,158047.000000,158047.000000,158047.000000,152234.000000,157813.000000
mean,116.395672,40.047275,38.182775,1026.798200,354.312894,176.397625,96.933881
std,0.395223,0.264798,5030.694816,5025.748455,17423.723518,106.382490,9748.857634
min,115.692222,39.718611,-21.300000,940.000000,4.000000,0.000000,0.000000
25%,116.194167,39.847500,2.500000,994.200000,27.000000,75.000000,0.900000
50%,116.290556,39.973889,13.800000,1005.600000,48.000000,184.000000,1.500000
75%,116.626944,40.223333,23.200000,1016.900000,73.000000,266.000000,2.500000
max,117.117778,40.658889,999999.000000,999999.000000,999999.000000,360.000000,999999.000000

In [10]:
# print time steps
time_me,ind_me=np.unique(df_me['utc_time'],return_inverse=True)
print('There are',len(time_me),'time steps in total')
print(time_me)
print(ind_me)

There are 8782 time steps in total
['2017-01-30 16:00:00' '2017-01-30 17:00:00' '2017-01-30 18:00:00' ...
 '2018-01-31 13:00:00' '2018-01-31 14:00:00' '2018-01-31 15:00:00']
[   0    1    2 ... 8779 8780 8781]

In [11]:
def weather_mode(seq):
    seq=list(seq)
    seq_class=np.unique(seq)
    freq=np.zeros(len(seq_class))
    for i in range(len(seq_class)):
        freq[i]=seq.count(seq_class[i])
    return(seq_class[np.argmax(freq)])

In [12]:
# aggregate the results
temperature,pressure,humidity,wind_direction,wind_speed,weather=list(),list(),list(),list(),list(),list()
for i in range(len(time_me)):
    temperature.append(np.nanmedian(df_me[ind_me==i]['temperature']))
    pressure.append(np.nanmedian(df_me[ind_me==i]['pressure']))
    humidity.append(np.nanmedian(df_me[ind_me==i]['humidity']))
    wind_direction.append(np.nanmedian(df_me[ind_me==i]['wind_direction']))
    wind_speed.append(np.nanmedian(df_me[ind_me==i]['wind_speed']))
    weather.append(weather_mode(df_me[ind_me==i]['weather']))

/Users/zhanght/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py:4033: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)

In [13]:
# create new df
df1_me=pd.DataFrame({
    'utc_time':time_me,
    'temperature':temperature,
    'pressure':pressure,
    'humidity':humidity,
    'wind_direction':wind_direction,
    'wind_speed':wind_speed,
    'weather':weather
})
df1_me

,humidity,pressure,temperature,utc_time,weather,wind_direction,wind_speed
0,16.0,1024.60,-2.85,2017-01-30 16:00:00,Sunny/clear,210.0,1.70
1,18.5,1024.40,-3.45,2017-01-30 17:00:00,Sunny/clear,215.0,1.40
2,19.0,1024.10,-3.65,2017-01-30 18:00:00,Sunny/clear,187.0,1.05
3,21.5,1023.55,-3.80,2017-01-30 19:00:00,Sunny/clear,224.0,1.10
4,24.0,1022.75,-4.10,2017-01-30 20:00:00,Sunny/clear,200.0,0.90
5,25.0,1022.35,-4.45,2017-01-30 21:00:00,Sunny/clear,202.5,0.80
6,27.5,1021.90,-4.70,2017-01-30 22:00:00,Sunny/clear,185.0,0.75
7,29.0,1022.00,-5.50,2017-01-30 23:00:00,Haze,154.5,0.70
8,31.5,1022.15,-6.20,2017-01-31 00:00:00,Sunny/clear,182.0,0.60
9,27.5,1022.15,-3.75,2017-01-31 01:00:00,Haze,228.0,0.70
10,20.0,1021.90,-1.10,2017-01-31 02:00:00,Haze,194.0,1.20
11,16.0,1021.90,0.60,2017-01-31 03:00:00,Sunny/clear,193.0,1.55
12,14.0,1020.80,2.00,2017-01-31 04:00:00,Sunny/clear,148.5,1.45
13,13.0,1019.60,3.25,2017-01-31 05:00:00,Sunny/clear,170.5,1.40
14,12.0,1018.80,4.00,2017-01-31 06:00:00,Sunny/clear,235.0,1.65
15,11.0,1018.40,4.55,2017-01-31 07:00:00,Sunny/clear,218.0,1.85
16,12.0,1018.85,4.50,2017-01-31 08:00:00,Sunny/clear,213.0,2.20
17,13.0,1019.55,3.30,2017-01-31 09:00:00,Sunny/clear,217.0,1.85
18,17.0,1020.25,1.05,2017-01-31 10:00:00,Sunny/clear,230.0,1.60
19,20.0,1021.25,-0.55,2017-01-31 11:00:00,Sunny/clear,246.0,1.55
20,23.0,1022.10,-2.20,2017-01-31 12:00:00,Sunny/clear,190.0,1.30
21,21.5,1023.05,-1.40,2017-01-31 13:00:00,Sunny/clear,86.5,1.65
22,20.5,1024.00,-1.70,2017-01-31 14:00:00,Sunny/clear,81.5,2.10
23,19.0,1025.15,-0.70,2017-01-31 15:00:00,Sunny/clear,45.5,1.95
24,20.5,1026.15,-1.00,2017-01-31 16:00:00,Sunny/clear,119.5,1.95
25,22.0,1026.70,-1.70,2017-01-31 17:00:00,Sunny/clear,67.0,1.95
26,23.0,1027.50,-2.50,2017-01-31 18:00:00,Sunny/clear,120.5,2.30
27,23.5,1028.05,-3.25,2017-01-31 19:00:00,Sunny/clear,60.0,2.25
28,24.5,1028.75,-3.85,2017-01-31 20:00:00,Sunny/clear,59.5,2.10
29,25.0,1029.70,-3.95,2017-01-31 21:00:00,Sunny/clear,50.5,2.15
...,...,...,...,...,...,...,...
8752,15.0,1018.25,1.90,2018-01-30 10:00:00,Sunny/clear,289.0,2.45
8753,18.0,1018.95,-0.65,2018-01-30 11:00:00,Sunny/clear,288.5,1.75
8754,18.0,1020.20,0.40,2018-01-30 12:00:00,Sunny/clear,294.5,2.30
8755,17.5,1021.15,-0.10,2018-01-30 13:00:00,Sunny/clear,311.0,2.05
8756,18.5,1022.15,-0.55,2018-01-30 14:00:00,Sunny/clear,298.0,2.15
8757,20.5,1022.80,-1.00,2018-01-30 15:00:00,Sunny/clear,311.0,1.95
8758,21.5,1023.05,-1.85,2018-01-30 16:00:00,Sunny/clear,309.0,2.20
8759,20.5,1023.65,-1.85,2018-01-30 17:00:00,Sunny/clear,299.0,2.15
8760,20.5,1023.85,-1.60,2018-01-30 18:00:00,Sunny/clear,299.0,2.70
8761,20.0,1023.35,-1.95,2018-01-30 19:00:00,Sunny/clear,308.5,2.70
8762,21.0,1023.05,-2.50,2018-01-30 20:00:00,Sunny/clear,299.5,2.15
8763,22.0,1023.20,-2.65,2018-01-30 21:00:00,Sunny/clear,305.0,1.95
8764,23.5,1023.60,-3.20,2018-01-30 22:00:00,Sunny/clear,271.5,1.45
8765,24.0,1023.85,-3.70,2018-01-30 23:00:00,Sunny/clear,257.5,1.70
8766,24.0,1023.85,-3.40,2018-01-31 00:00:00,Sunny/clear,244.0,1.90
8767,21.0,1023.95,-1.80,2018-01-31 01:00:00,Sunny/clear,171.5,2.00
8768,18.5,1023.75,-0.65,2018-01-31 02:00:00,Sunny/clear,321.0,2.65
8769,16.5,1022.95,0.60,2018-01-31 03:00:00,Sunny/clear,174.5,2.65
8770,15.0,1021.95,1.60,2018-01-31 04:00:00,Sunny/clear,259.5,2.80
8771,14.0,1020.90,2.55,2018-01-31 05:00:00,Sunny/clear,267.0,3.40
8772,13.0,1020.05,3.10,2018-01-31 06:00:00,Sunny/clear,214.0,2.85
8773,13.5,1019.60,3.30,2018-01-31 07:00:00,Sunny/clear,222.0,2.80
8774,13.0,1019.40,3.20,2018-01-31 08:00:00,Sunny/clear,228.0,1.80
8775,15.0,1019.55,2.30,2018-01-31 09:00:00,Sunny/clear,241.0,1.45
8776,20.0,1020.05,-0.25,2018-01-31 10:00:00,Sunny/clear,248.5,1.35
8777,24.0,1020.45,-2.90,2018-01-31 11:00:00,Sunny/clear,214.0,1.25
8778,27.0,1020.65,-3.15,2018-01-31 12:00:00,Sunny/clear,234.5,1.45
8779,28.5,1020.85,-4.15,2018-01-31 13:00:00,Sunny/clear,228.0,1.30
8780,32.5,1020.70,-5.10,2018-01-31 14:00:00,Sunny/clear,190.5,0.95
8781,35.0,1020.45,-5.60,2018-01-31 15:00:00,Sunny/clear,264.0,1.05

In [14]:
# same the processed data
df1_me.to_csv(root_dir+'me_17.csv')

# Merge the data

In [15]:
# data merge
left=df1_aq
right=df1_me
df_merge=pd.merge(left, right, how='right', on='utc_time')
df_merge=df_merge.sort_values(by='utc_time',ascending=True)
df_merge.index=np.arange(0,len(df1_me['utc_time']))

In [16]:
df_merge

,PM2.5,utc_time,humidity,pressure,temperature,weather,wind_direction,wind_speed
0,82.558824,2017-01-30 16:00:00,16.0,1024.60,-2.85,Sunny/clear,210.0,1.70
1,89.764706,2017-01-30 17:00:00,18.5,1024.40,-3.45,Sunny/clear,215.0,1.40
2,94.029412,2017-01-30 18:00:00,19.0,1024.10,-3.65,Sunny/clear,187.0,1.05
3,92.558824,2017-01-30 19:00:00,21.5,1023.55,-3.80,Sunny/clear,224.0,1.10
4,92.176471,2017-01-30 20:00:00,24.0,1022.75,-4.10,Sunny/clear,200.0,0.90
5,93.352941,2017-01-30 21:00:00,25.0,1022.35,-4.45,Sunny/clear,202.5,0.80
6,92.147059,2017-01-30 22:00:00,27.5,1021.90,-4.70,Sunny/clear,185.0,0.75
7,97.558824,2017-01-30 23:00:00,29.0,1022.00,-5.50,Haze,154.5,0.70
8,98.545455,2017-01-31 00:00:00,31.5,1022.15,-6.20,Sunny/clear,182.0,0.60
9,101.969697,2017-01-31 01:00:00,27.5,1022.15,-3.75,Haze,228.0,0.70
10,103.823529,2017-01-31 02:00:00,20.0,1021.90,-1.10,Haze,194.0,1.20
11,99.676471,2017-01-31 03:00:00,16.0,1021.90,0.60,Sunny/clear,193.0,1.55
12,86.588235,2017-01-31 04:00:00,14.0,1020.80,2.00,Sunny/clear,148.5,1.45
13,80.090909,2017-01-31 05:00:00,13.0,1019.60,3.25,Sunny/clear,170.5,1.40
14,74.242424,2017-01-31 06:00:00,12.0,1018.80,4.00,Sunny/clear,235.0,1.65
15,65.812500,2017-01-31 07:00:00,11.0,1018.40,4.55,Sunny/clear,218.0,1.85
16,65.843750,2017-01-31 08:00:00,12.0,1018.85,4.50,Sunny/clear,213.0,2.20
17,65.352941,2017-01-31 09:00:00,13.0,1019.55,3.30,Sunny/clear,217.0,1.85
18,68.161290,2017-01-31 10:00:00,17.0,1020.25,1.05,Sunny/clear,230.0,1.60
19,82.000000,2017-01-31 11:00:00,20.0,1021.25,-0.55,Sunny/clear,246.0,1.55
20,85.483871,2017-01-31 12:00:00,23.0,1022.10,-2.20,Sunny/clear,190.0,1.30
21,80.903226,2017-01-31 13:00:00,21.5,1023.05,-1.40,Sunny/clear,86.5,1.65
22,52.096774,2017-01-31 14:00:00,20.5,1024.00,-1.70,Sunny/clear,81.5,2.10
23,35.419355,2017-01-31 15:00:00,19.0,1025.15,-0.70,Sunny/clear,45.5,1.95
24,24.838710,2017-01-31 16:00:00,20.5,1026.15,-1.00,Sunny/clear,119.5,1.95
25,20.774194,2017-01-31 17:00:00,22.0,1026.70,-1.70,Sunny/clear,67.0,1.95
26,16.548387,2017-01-31 18:00:00,23.0,1027.50,-2.50,Sunny/clear,120.5,2.30
27,12.548387,2017-01-31 19:00:00,23.5,1028.05,-3.25,Sunny/clear,60.0,2.25
28,9.548387,2017-01-31 20:00:00,24.5,1028.75,-3.85,Sunny/clear,59.5,2.10
29,8.677419,2017-01-31 21:00:00,25.0,1029.70,-3.95,Sunny/clear,50.5,2.15
...,...,...,...,...,...,...,...,...
8752,15.121212,2018-01-30 10:00:00,15.0,1018.25,1.90,Sunny/clear,289.0,2.45
8753,19.941176,2018-01-30 11:00:00,18.0,1018.95,-0.65,Sunny/clear,288.5,1.75
8754,19.323529,2018-01-30 12:00:00,18.0,1020.20,0.40,Sunny/clear,294.5,2.30
8755,15.235294,2018-01-30 13:00:00,17.5,1021.15,-0.10,Sunny/clear,311.0,2.05
8756,10.647059,2018-01-30 14:00:00,18.5,1022.15,-0.55,Sunny/clear,298.0,2.15
8757,10.363636,2018-01-30 15:00:00,20.5,1022.80,-1.00,Sunny/clear,311.0,1.95
8758,9.575758,2018-01-30 16:00:00,21.5,1023.05,-1.85,Sunny/clear,309.0,2.20
8759,10.382353,2018-01-30 17:00:00,20.5,1023.65,-1.85,Sunny/clear,299.0,2.15
8760,8.823529,2018-01-30 18:00:00,20.5,1023.85,-1.60,Sunny/clear,299.0,2.70
8761,10.645161,2018-01-30 19:00:00,20.0,1023.35,-1.95,Sunny/clear,308.5,2.70
8762,12.516129,2018-01-30 20:00:00,21.0,1023.05,-2.50,Sunny/clear,299.5,2.15
8763,11.766667,2018-01-30 21:00:00,22.0,1023.20,-2.65,Sunny/clear,305.0,1.95
8764,13.833333,2018-01-30 22:00:00,23.5,1023.60,-3.20,Sunny/clear,271.5,1.45
8765,14.500000,2018-01-30 23:00:00,24.0,1023.85,-3.70,Sunny/clear,257.5,1.70
8766,17.233333,2018-01-31 00:00:00,24.0,1023.85,-3.40,Sunny/clear,244.0,1.90
8767,20.333333,2018-01-31 01:00:00,21.0,1023.95,-1.80,Sunny/clear,171.5,2.00
8768,19.281250,2018-01-31 02:00:00,18.5,1023.75,-0.65,Sunny/clear,321.0,2.65
8769,18.387097,2018-01-31 03:00:00,16.5,1022.95,0.60,Sunny/clear,174.5,2.65
8770,16.652174,2018-01-31 04:00:00,15.0,1021.95,1.60,Sunny/clear,259.5,2.80
8771,14.906250,2018-01-31 05:00:00,14.0,1020.90,2.55,Sunny/clear,267.0,3.40
8772,15.617647,2018-01-31 06:00:00,13.0,1020.05,3.10,Sunny/clear,214.0,2.85
8773,17.764706,2018-01-31 07:00:00,13.5,1019.60,3.30,Sunny/clear,222.0,2.80
8774,21.676471,2018-01-31 08:00:00,13.0,1019.40,3.20,Sunny/clear,228.0,1.80
8775,24.588235,2018-01-31 09:00:00,15.0,1019.55,2.30,Sunny/clear,241.0,1.45
8776,29.764706,2018-01-31 10:00:00,20.0,1020.05,-0.25,Sunny/clear,248.5,1.35
8777,33.363636,2018-01-31 11:00:00,24.0,1020.45,-2.90,Sunny/clear,214.0,1.25
8778,42.000000,2018-01-31 12:00:00,27.0,1020.65,-3.15,Sunny/clear,234.5,1.45
8779,46.176471,2018-01-31 13:00:00,28.5,1020.85,-4.15,Sunny/clear,228.0,1.30
8780,48.117647,2018-01-31 14:00:00,32.5,1020.70,-5.10,Sunny/clear,190.5,0.95
8781,48.558824,2018-01-31 15:00:00,35.0,1020.45,-5.60,Sunny/clear,264.0,1.05

In [17]:
df_merge.to_csv(root_dir+'merge_17_original.csv')

# NaN Imputation V1
I here make use of external [datasets](http://beijingair.sinaapp.com) to fill the NaN partially.

In [18]:
# locate the NaNs
n=len(df_merge['utc_time'])
ind_nan=np.arange(0,n)
ind_nan=ind_nan[df_merge['PM2.5'].isna()]
print(ind_nan[:10])
np.sum(df_merge.isna())

[149 167 168 172 173 175 186 187 190 205]

PM2.5             757
utc_time            0
humidity            0
pressure            0
temperature         0
weather             0
wind_direction     13
wind_speed         13
dtype: int64

In [19]:
# set directories of external data folders
lib17_fdr='beijing_20170101-20171231/'
lib18_fdr='beijing_20180101-20180602/'

In [20]:
def time_extract(utc_time):
    date=utc_time[:4]+utc_time[5:7]+utc_time[8:10]
    hour=utc_time[11:13]
    return date,hour

In [21]:
nan_seq=list()
for ind in ind_nan:
    utc_time=df_merge['utc_time'][ind]
    date,hour=time_extract(utc_time)

    if utc_time[3]=='7':
        lib_dir=root_dir+lib17_fdr+'beijing_all_'+date+'.csv'
    else:
        lib_dir=root_dir+lib18_fdr+'beijing_all_'+date+'.csv'

    df_lib=pd.read_csv(lib_dir)
    # avoid error in lib
    if df_lib.shape[1]!=38:
        nan_seq.append(np.nan)
        continue
    
    df_lib=df_lib[df_lib['hour']==int(hour)]
    
    # avoid missing data in lib
    if df_lib.shape[0]==0:
        nan_seq.append(np.nan)
    else:
        nan_seq.append(np.nanmean(list(df_lib.iloc[0,3:])))

/Users/zhanght/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:23: RuntimeWarning: Mean of empty slice

In [22]:
df_merge['PM2.5'][ind_nan]=nan_seq

/Users/zhanght/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
# show the rest missing part of the data
np.sum(df_merge.isna())

PM2.5             548
utc_time            0
humidity            0
pressure            0
temperature         0
weather             0
wind_direction     13
wind_speed         13
dtype: int64

In [24]:
# save
df_merge.to_csv(root_dir+'merge_17_v1.csv')

# NaN Imputation V2
[The median of medians](https://biendata.com/forum/view_post_category/170) method will be introduced to resolve remained missing data.

## PM2.5

In [25]:
ind_nan=np.arange(0,n)
ind_nan=ind_nan[df_merge['PM2.5'].isna()]
print(ind_nan[:10])

[175 218 223 224 227 229 230 504 512 517]

In [26]:
# median of medians
def MedoMeds(df,colname,ind,win_seq=list([3,6,12,24,36,48,60,72,84,96,108,120,144,168,264,336])):
    # df : data frame
    # colname : column name of target variable
    # ind : index of variable
    med_seq=list()
    for i in range(len(win_seq)):
        win=win_seq[i]
        med_seq.append(np.nanmedian(df[colname][np.max((ind-win-1),0):(ind-1)]))
    return np.nanmedian(med_seq)

In [27]:
nan_seq=list()
for ind in ind_nan:
    nan_seq.append(MedoMeds(df_merge,'PM2.5',ind))
df_merge['PM2.5'][ind_nan]=nan_seq

/Users/zhanght/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1018: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/zhanght/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py:4033: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
/Users/zhanght/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [28]:
np.sum(df_merge.isna())

PM2.5              0
utc_time           0
humidity           0
pressure           0
temperature        0
weather            0
wind_direction    13
wind_speed        13
dtype: int64

## Wind speed

In [29]:
ind_nan=np.arange(0,n)
ind_nan=ind_nan[df_merge['wind_speed'].isna()]
print(ind_nan[:10])

nan_seq=list()
for ind in ind_nan:
    nan_seq.append(MedoMeds(df_merge,'wind_speed',ind,win_seq=list([3,6,12,24,36,48])))
df_merge['wind_speed'][ind_nan]=nan_seq

np.sum(df_merge.isna())

[8155 8156 8157 8158 8159 8160 8161 8162 8163 8164]

/Users/zhanght/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py:4033: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
/Users/zhanght/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

PM2.5              0
utc_time           0
humidity           0
pressure           0
temperature        0
weather            0
wind_direction    13
wind_speed         0
dtype: int64

## Wind Direction

In [30]:
ind_nan=np.arange(0,n)
ind_nan=ind_nan[df_merge['wind_direction'].isna()]
print(ind_nan[:10])

nan_seq=list()
for ind in ind_nan:
    nan_seq.append(MedoMeds(df_merge,'wind_direction',ind,win_seq=list([3,6,12,24,36,48])))
df_merge['wind_direction'][ind_nan]=nan_seq

np.sum(df_merge.isna())

[8155 8156 8157 8158 8159 8160 8161 8162 8163 8164]

/Users/zhanght/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py:4033: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
/Users/zhanght/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

PM2.5             0
utc_time          0
humidity          0
pressure          0
temperature       0
weather           0
wind_direction    0
wind_speed        0
dtype: int64

In [31]:
df_merge.to_csv('merge_17_v2.csv')